# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Wed Nov 11 15:27:40 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(339, 206)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.push_Iniciar = QtGui.QPushButton(self.centralwidget)
        self.push_Iniciar.setGeometry(QtCore.QRect(10, 150, 51, 29))
        self.push_Iniciar.setObjectName(_fromUtf8("push_Iniciar"))
        self.push_Salir = QtGui.QPushButton(self.centralwidget)
        self.push_Salir.setGeometry(QtCore.QRect(70, 150, 51, 29))
        self.push_Salir.setObjectName(_fromUtf8("push_Salir"))
        self.layoutWidget_5 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_5.setGeometry(QtCore.QRect(130, 10, 201, 161))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_11 = QtGui.QGroupBox(self.layoutWidget_5)
        self.groupBox_11.setMaximumSize(QtCore.QSize(220, 400))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.progressBar_CH3 = QtGui.QProgressBar(self.groupBox_11)
        self.progressBar_CH3.setProperty("value", 100)
        self.progressBar_CH3.setTextVisible(False)
        self.progressBar_CH3.setObjectName(_fromUtf8("progressBar_CH3"))
        self.gridLayout.addWidget(self.progressBar_CH3, 2, 1, 1, 1)
        self.progressBar_CH2 = QtGui.QProgressBar(self.groupBox_11)
        self.progressBar_CH2.setProperty("value", 100)
        self.progressBar_CH2.setTextVisible(False)
        self.progressBar_CH2.setObjectName(_fromUtf8("progressBar_CH2"))
        self.gridLayout.addWidget(self.progressBar_CH2, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.progressBar_CH1 = QtGui.QProgressBar(self.groupBox_11)
        self.progressBar_CH1.setProperty("value", 100)
        self.progressBar_CH1.setTextVisible(False)
        self.progressBar_CH1.setObjectName(_fromUtf8("progressBar_CH1"))
        self.gridLayout.addWidget(self.progressBar_CH1, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.label_GyroX = QtGui.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_GyroX.setFont(font)
        self.label_GyroX.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.label_GyroX.setText(_fromUtf8(""))
        self.label_GyroX.setAlignment(QtCore.Qt.AlignCenter)
        self.label_GyroX.setObjectName(_fromUtf8("label_GyroX"))
        self.gridLayout.addWidget(self.label_GyroX, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 2, 1, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_11)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_11)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_1 = QtGui.QLabel(self.groupBox_11)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout_4.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_11)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 2, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_11)
        self.layoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 10, 121, 131))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_12 = QtGui.QGroupBox(self.layoutWidget_6)
        self.groupBox_12.setMaximumSize(QtCore.QSize(220, 400))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.progressBar_Bat = QtGui.QProgressBar(self.groupBox_12)
        self.progressBar_Bat.setMaximum(100)
        self.progressBar_Bat.setProperty("value", 0)
        self.progressBar_Bat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.progressBar_Bat.setTextVisible(True)
        self.progressBar_Bat.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_Bat.setInvertedAppearance(False)
        self.progressBar_Bat.setTextDirection(QtGui.QProgressBar.BottomToTop)
        self.progressBar_Bat.setObjectName(_fromUtf8("progressBar_Bat"))
        self.gridLayout_5.addWidget(self.progressBar_Bat, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_12)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Interfaz EEG/PC/RobotArm", None, QtGui.QApplication.UnicodeUTF8))
        self.push_Iniciar.setText(QtGui.QApplication.translate("MainWindow", "Iniciar", None, QtGui.QApplication.UnicodeUTF8))
        self.push_Salir.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("MainWindow", "Calidad de los Canales", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "CH3 F8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "CH2 AF3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_1.setText(QtGui.QApplication.translate("MainWindow", "CH1 O2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Gyro (X)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Nivel de Bateria", None, QtGui.QApplication.UnicodeUTF8))

